---

- name: Install Homebrew
  shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

- name: Homebrew Cask repository
  homebrew_tap:
    tap: homebrew/cask
    state: present
  ignore_errors: yes

- name: Install Sublime Text
  homebrew_cask:
    name: sublime-text
    state: present
  ignore_errors: yes

- name: Install VSCode
  homebrew_cask:
    name: visual-studio-code
    state: present
  ignore_errors: yes

- name: Install Slack
  homebrew_cask:
    name: slack
    state: present
  ignore_errors: yes

- name: Install Node
  homebrew_cask:
    name: node
    state: present
  ignore_errors: yes

- name: Install Chrome
  homebrew_cask:
    name: google-chrome
    state: present
  ignore_errors: yes


- name: Install Zoom
  homebrew_cask:
    name: zoom
    state: present
  ignore_errors: yes

- name: Install GitHub
  homebrew_cask:
    name: github
    state: present
  ignore_errors: yes