---
- name: Homebrew Cask repository
  homebrew_tap:
    tap: homebrew/cask
    state: absent
  ignore_errors: yes

- name: Uninstall Sublime Text
  homebrew_cask:
    name: sublime-text
    state: absent
  ignore_errors: yes

- name: Uninstall VSCode
  homebrew_cask:
    name: visual-studio-code
    state: absent
  ignore_errors: yes

- name: Uninstall Slack
  homebrew_cask:
    name: slack
    state: absent
  ignore_errors: yes

- name: Uninstall Python
  brew:
    name: python3
    state: absent
  ignore_errors: yes

- name: Uninstall Pip
  brew:
    name: pip
    state: absent
  ignore_errors: yes

- name: Uninstall Django
  pip:
    name: django
    state: absent
  ignore_errors: yes

- name: Uninstall Firefox
  homebrew_cask:
    name: firefox
    state: absent
  ignore_errors: yes

- name: Uninstall Zoom
  homebrew_cask:
    name: zoom
    state: absent
  ignore_errors: yes

- name: Uninstall GitHub
  homebrew_cask:
    name: github
    state: absent
  ignore_errors: yes
